---
- name: write the interfaces file
  ansible.builtin.template: 
    src: spine-interfaces.j2
    dest: /etc/network/interfaces
  notify:
    - reload interfaces

- name: write the frr file
  ansible.builtin.template: 
    src: spine-frr.conf.j2
    dest: /etc/frr/frr.conf
  notify:
    - restart frr

