---
- name: apt upgrade
  apt: 
    update_cache: yes
    autoremove: yes
    upgrade: dist
    allow_unauthenticated: yes
    dpkg_options: 'force-confold'

- name: reboot system
  shell: sleep 2 && shutdown -r now "Ansible upgrade"
  async: 1
  poll: 0
  ignore_errors: true

- pause: 
    seconds: 5

- name: waiting for switch to come back
  become: false
  wait_for_connection: 
    timeout: 300
